# Generated by Django 6.0.4 on 2026-04-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_middle_initial_profile_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
