# Generated by Django 6.0.4 on 2026-04-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_failed_attempts_profile_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmirecord',
            name='sex',
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unit',
            field=models.CharField(max_length=100),
        ),
    ]
