# Generated by Django 6.0.4 on 2026-04-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_bmirecord_sex_alter_profile_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personnel_type',
            field=models.CharField(default='PNCO', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bmirecord',
            name='pnp_classification',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bmirecord',
            name='who_classification',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
