# Generated by Django 6.0.4 on 2026-04-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_personnel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='personnel_type',
            field=models.CharField(choices=[('PCO', 'PCO'), ('PNCO', 'PNCO'), ('NUP', 'NUP')], default='PNCO', max_length=10),
        ),
    ]
