# Generated by Django 6.0.4 on 2026-04-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_personnel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmirecord',
            old_name='max_normal_weight',
            new_name='maximum_normal_weight',
        ),
        migrations.RemoveField(
            model_name='bmirecord',
            name='pnp_classification',
        ),
        migrations.RemoveField(
            model_name='bmirecord',
            name='who_classification',
        ),
        migrations.AddField(
            model_name='bmirecord',
            name='pnp_bmi_classification',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bmirecord',
            name='who_bmi_classification',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
    ]
