# Generated by Django 6.0.4 on 2026-04-26 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_loginattempt_success_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmirecord',
            old_name='created_at',
            new_name='date_computed',
        ),
        migrations.RenameField(
            model_name='bmirecord',
            old_name='pnp_bmi_classification',
            new_name='pnp_class',
        ),
        migrations.RenameField(
            model_name='bmirecord',
            old_name='who_bmi_classification',
            new_name='who_class',
        ),
        migrations.RemoveField(
            model_name='bmirecord',
            name='hip',
        ),
        migrations.RemoveField(
            model_name='bmirecord',
            name='maximum_normal_weight',
        ),
        migrations.RemoveField(
            model_name='bmirecord',
            name='waist',
        ),
        migrations.RemoveField(
            model_name='bmirecord',
            name='weight_to_lose',
        ),
        migrations.RemoveField(
            model_name='bmirecord',
            name='wrist',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_locked',
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(default='2026-4-26'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='otp_created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personnel_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='unit',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
