# Generated by Django 6.0.4 on 2026-04-26 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_created_at_bmirecord_date_computed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bmirecord',
            name='hip',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bmirecord',
            name='max_weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bmirecord',
            name='waist',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bmirecord',
            name='weight_to_lose',
            field=models.CharField(default='0.0 kg', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bmirecord',
            name='wrist',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otp_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personnel_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.CharField(max_length=100),
        ),
    ]
