# Generated by Django 6.0.4 on 2026-04-26 04:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_bmirecord_hip_bmirecord_max_weight_bmirecord_waist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginattempt',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='bmirecord',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='bmirecord',
            name='date_computed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bmirecord',
            name='weight_to_lose',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personnel_type',
            field=models.CharField(choices=[('Uniformed', 'Uniformed'), ('Non-Uniformed', 'Non-Uniformed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unit',
            field=models.CharField(max_length=150),
        ),
    ]
