# Generated by Django 6.0.4 on 2026-04-26 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_loginattempt_ip_address_bmirecord_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmirecord',
            old_name='max_weight',
            new_name='maximum_normal_weight',
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
