# Generated by Django 6.0.4 on 2026-04-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_max_weight_bmirecord_maximum_normal_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='personnel_type',
            field=models.CharField(choices=[('PCO', 'Police Commissioned Officer (PCO)'), ('PNCO', 'Police Non-Commissioned Officer (PNCO)'), ('NUP', 'Non-Uniformed Personnel (NUP)')], max_length=10),
        ),
    ]
